#!/bin/bash

echo $PWD
git submodule init
git submodule update

# Change to the submodule directory
cd ../../afl

# Build the submodule using the Makefile
make

# Change back to the parent directory
cd ..