#!/bin/bash

echo "$PWD"
git submodule update --init --recursive

# Change to the submodule directory
# shellcheck disable=SC2164
cd ../../afl

# Build the submodule using the Makefile
make

# Change back to the parent directory
# shellcheck disable=SC2103
cd ..